### ISSUE TITLE
Error getting show list from SRF (ValueError)

### ISSUE THREAD

**Issue by l0rn0r** [goggle/script.module.srgssr#3]
Hi goggle
Thanks for your work!
Since yesterday I do have problems with the SRF Play TV addon - always when I want to list concrete shows (not only show names - e.g. menu point "Newest favorite shows"), I get an error - it says "ValueError: No JSON object could be decoded".

Looking at the log, I found the following problem (in this example, there is only one show in favorites, "Babylon Berlin"):
```log
2020-05-13 14:14:50.109 T:1799328640   DEBUG: CAddonSettings[plugin.video.srfplaytv]: loading setting definitions  
2020-05-13 14:14:50.110 T:1799328640   DEBUG: CAddonSettings[plugin.video.srfplaytv]: trying to load setting definitions from old format...  
2020-05-13 14:14:50.111 T:1799328640   DEBUG: CAddonSettings[plugin.video.srfplaytv]: loading setting values  
2020-05-13 14:14:50.112 T:1799328640   DEBUG: script.module.srgssr-1.7.0-build_newest_favourite_menu  
2020-05-13 14:14:50.113 T:1799328640   DEBUG: script.module.srgssr-1.7.0-build_newest_favourite_menu. Open URL https://www.srf.ch/play/tv/show/d12a798e-c300-4816-b627-68e075823549/latestEpisodes?numberOfEpisodes=30&tillMonth=05-2020.  
2020-05-13 14:14:50.113 T:1799328640   DEBUG: script.module.srgssr-1.7.0-open_url, url = https://www.srf.ch/play/tv/show/d12a798e-c300-4816-b627-68e075823549/latestEpisodes?numberOfEpisodes=30&tillMonth=05-2020  
2020-05-13 14:14:50.126 T:1799328640   DEBUG: Skin Helper Simplecache --> Closed  
2020-05-13 14:14:50.126 T:1799328640   ERROR: EXCEPTION Thrown (PythonToCppException)  : -->Python callback/script returned the following error<--  
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!  
                                            Error Type: <type 'exceptions.ValueError'>  
                                            Error Contents: No JSON object could be decoded  
                                            Traceback (most recent call last):  
                                              File "/storage/.kodi/addons/plugin.video.srfplaytv/addon.py", line 23, in <module>  
                                                srfplaytv.run()  
                                              File "/storage/.kodi/addons/plugin.video.srfplaytv/resources/lib/srfplaytv.py", line 120, in run  
                                                SRFPlayTV().build_newest_favourite_menu(page=page)  
                                              File "/storage/.kodi/addons/script.module.srgssr/lib/srgssr.py", line 534, in build_newest_favourite_menu  
                                                response = json.loads(self.open_url(json_url))  
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads  
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode  
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode  
                                            ValueError: No JSON object could be decoded  
                                            -->End of Python script error report<--  
2020-05-13 14:14:50.126 T:1799328640   DEBUG: onExecutionDone(27, /storage/.kodi/addons/plugin.video.srfplaytv/addon.py)  
2020-05-13 14:14:50.200 T:1937465360   DEBUG: ------ Window Init (DialogNotification.xml) ------  
2020-05-13 14:14:50.386 T:1799328640    INFO: Python interpreter stopped  
2020-05-13 14:14:50.386 T:1799328640   DEBUG: Thread LanguageInvoker 1799328640 terminating  
2020-05-13 14:14:50.387 T:1627059072   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender plugin.video.youtube - method: Other.check_settings  - data: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20false%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]  
2020-05-13 14:14:50.398 T:1543132032   ERROR: GetDirectory - Error getting plugin://plugin.video.srfplaytv/?mode=12&name=Newest_Favourite_Shows  
2020-05-13 14:14:50.399 T:1543132032   DEBUG: Thread waiting 1543132032 terminating  
```
I'm running SRF Play TV **1.6.0** with script.module.srgssr **1.7.0** on LibreELEC **9.2.1**.

Any idea how to fix this? Did SRF change something in their URL-structure?
Thanks and e gruess

**Comment by goggle** [comment]
Thanks for reporting this. I will have a look.

**Comment by xmentos** [comment]
The version from the PR #6 works for several of the RTS menus but not for 'Recommendations' and 'Newest videos (by topic)'. I'm trying to fix this but I have troubles finding information on the API v3, @joachimBurket or @tobiaswaldvogel can you point me in the right direction?

**Comment by tobiaswaldvogel** [comment]
There is no official documentation. I used the Chrome developer tools for
the reverse engineering. Just navigate to the SRF page on your browser,
press F12, look for your functionality you want and then check the rest API
calls in the network tab ;-)


xmentos ***@***.***> schrieb am Di., 23. Nov. 2021, 17:10:

**Comment by goggle** [comment]
This has been fixed on the `master` branch.
I will release the plugin for Kodi Matrix soon.
